# Form implementation generated from reading ui file 'frmAdministrarBodegas.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmAdministrarBodegas(object):
    def setupUi(self, frmAdministrarBodegas):
        frmAdministrarBodegas.setObjectName("frmAdministrarBodegas")
        frmAdministrarBodegas.resize(400, 135)
        self.label = QtWidgets.QLabel(parent=frmAdministrarBodegas)
        self.label.setGeometry(QtCore.QRect(10, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnEliminarBod = QtWidgets.QPushButton(parent=frmAdministrarBodegas)
        self.btnEliminarBod.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.btnEliminarBod.setObjectName("btnEliminarBod")
        self.btnCrear = QtWidgets.QPushButton(parent=frmAdministrarBodegas)
        self.btnCrear.setGeometry(QtCore.QRect(10, 100, 91, 23))
        self.btnCrear.setObjectName("btnCrear")
        self.cmbBodegas = QtWidgets.QComboBox(parent=frmAdministrarBodegas)
        self.cmbBodegas.setGeometry(QtCore.QRect(200, 30, 131, 22))
        self.cmbBodegas.setObjectName("cmbBodegas")

        self.retranslateUi(frmAdministrarBodegas)
        QtCore.QMetaObject.connectSlotsByName(frmAdministrarBodegas)

    def retranslateUi(self, frmAdministrarBodegas):
        _translate = QtCore.QCoreApplication.translate
        frmAdministrarBodegas.setWindowTitle(_translate("frmAdministrarBodegas", "Administrar Bodegas"))
        self.label.setText(_translate("frmAdministrarBodegas", "Numero de bodega a eliminar:"))
        self.btnEliminarBod.setText(_translate("frmAdministrarBodegas", "EliminarBodega"))
        self.btnCrear.setText(_translate("frmAdministrarBodegas", "Crear Bodega"))
