# Form implementation generated from reading ui file 'AsignarDistribuidores.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogDistribuidores(object):
    def setupUi(self, DialogDistribuidores):
        DialogDistribuidores.setObjectName("DialogDistribuidores")
        DialogDistribuidores.resize(424, 217)
        self.LblPerfilDistribuidores = QtWidgets.QLabel(parent=DialogDistribuidores)
        self.LblPerfilDistribuidores.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblPerfilDistribuidores.setFont(font)
        self.LblPerfilDistribuidores.setObjectName("LblPerfilDistribuidores")
        self.LblNombre = QtWidgets.QLabel(parent=DialogDistribuidores)
        self.LblNombre.setGeometry(QtCore.QRect(20, 100, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblNombre.setFont(font)
        self.LblNombre.setObjectName("LblNombre")
        self.txtNombreDistribuidores = QtWidgets.QLineEdit(parent=DialogDistribuidores)
        self.txtNombreDistribuidores.setGeometry(QtCore.QRect(20, 120, 131, 20))
        self.txtNombreDistribuidores.setObjectName("txtNombreDistribuidores")
        self.LblCodigo = QtWidgets.QLabel(parent=DialogDistribuidores)
        self.LblCodigo.setGeometry(QtCore.QRect(20, 50, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblCodigo.setFont(font)
        self.LblCodigo.setObjectName("LblCodigo")
        self.txtCodigoDistribuidores = QtWidgets.QLineEdit(parent=DialogDistribuidores)
        self.txtCodigoDistribuidores.setGeometry(QtCore.QRect(20, 70, 131, 20))
        self.txtCodigoDistribuidores.setObjectName("txtCodigoDistribuidores")
        self.TblPerfiles = QtWidgets.QTableWidget(parent=DialogDistribuidores)
        self.TblPerfiles.setGeometry(QtCore.QRect(190, 20, 211, 181))
        self.TblPerfiles.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.TblPerfiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.TblPerfiles.setObjectName("TblPerfiles")
        self.TblPerfiles.setColumnCount(2)
        self.TblPerfiles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TblPerfiles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TblPerfiles.setHorizontalHeaderItem(1, item)
        self.BtnAnadir = QtWidgets.QPushButton(parent=DialogDistribuidores)
        self.BtnAnadir.setGeometry(QtCore.QRect(20, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnAnadir.setFont(font)
        self.BtnAnadir.setObjectName("BtnAnadir")

        self.retranslateUi(DialogDistribuidores)
        QtCore.QMetaObject.connectSlotsByName(DialogDistribuidores)

    def retranslateUi(self, DialogDistribuidores):
        _translate = QtCore.QCoreApplication.translate
        DialogDistribuidores.setWindowTitle(_translate("DialogDistribuidores", "Dialog"))
        self.LblPerfilDistribuidores.setText(_translate("DialogDistribuidores", "Añadir distribuidores"))
        self.LblNombre.setText(_translate("DialogDistribuidores", "Nombre del distribuidor"))
        self.LblCodigo.setText(_translate("DialogDistribuidores", "Codigo del distribuidor"))
        item = self.TblPerfiles.horizontalHeaderItem(0)
        item.setText(_translate("DialogDistribuidores", "Cod_Distribuidor"))
        item = self.TblPerfiles.horizontalHeaderItem(1)
        item.setText(_translate("DialogDistribuidores", "Nombre"))
        self.BtnAnadir.setText(_translate("DialogDistribuidores", "Añadir distribuidor"))
