# Form implementation generated from reading ui file 'frmRegistrarArticulo.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgRegistrarArticulo(object):
    def setupUi(self, DlgRegistrarArticulo):
        DlgRegistrarArticulo.setObjectName("DlgRegistrarArticulo")
        DlgRegistrarArticulo.resize(288, 263)
        self.LblDatos = QtWidgets.QLabel(parent=DlgRegistrarArticulo)
        self.LblDatos.setGeometry(QtCore.QRect(20, 20, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LblDatos.setFont(font)
        self.LblDatos.setObjectName("LblDatos")
        self.txtCodigo = QtWidgets.QLineEdit(parent=DlgRegistrarArticulo)
        self.txtCodigo.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.txtCodigo.setObjectName("txtCodigo")
        self.LblCodigo = QtWidgets.QLabel(parent=DlgRegistrarArticulo)
        self.LblCodigo.setGeometry(QtCore.QRect(20, 70, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblCodigo.setFont(font)
        self.LblCodigo.setObjectName("LblCodigo")
        self.LblNombre = QtWidgets.QLabel(parent=DlgRegistrarArticulo)
        self.LblNombre.setGeometry(QtCore.QRect(20, 100, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblNombre.setFont(font)
        self.LblNombre.setObjectName("LblNombre")
        self.txtNombre = QtWidgets.QLineEdit(parent=DlgRegistrarArticulo)
        self.txtNombre.setGeometry(QtCore.QRect(100, 100, 113, 20))
        self.txtNombre.setObjectName("txtNombre")
        self.LblPrecio = QtWidgets.QLabel(parent=DlgRegistrarArticulo)
        self.LblPrecio.setGeometry(QtCore.QRect(20, 130, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblPrecio.setFont(font)
        self.LblPrecio.setObjectName("LblPrecio")
        self.txtPrecio = QtWidgets.QLineEdit(parent=DlgRegistrarArticulo)
        self.txtPrecio.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.txtPrecio.setObjectName("txtPrecio")
        self.LblCantidad = QtWidgets.QLabel(parent=DlgRegistrarArticulo)
        self.LblCantidad.setGeometry(QtCore.QRect(20, 160, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblCantidad.setFont(font)
        self.LblCantidad.setObjectName("LblCantidad")
        self.txtCantidad = QtWidgets.QLineEdit(parent=DlgRegistrarArticulo)
        self.txtCantidad.setGeometry(QtCore.QRect(100, 160, 113, 20))
        self.txtCantidad.setObjectName("txtCantidad")
        self.BtnResgistrar = QtWidgets.QPushButton(parent=DlgRegistrarArticulo)
        self.BtnResgistrar.setGeometry(QtCore.QRect(20, 210, 81, 31))
        self.BtnResgistrar.setObjectName("BtnResgistrar")

        self.retranslateUi(DlgRegistrarArticulo)
        QtCore.QMetaObject.connectSlotsByName(DlgRegistrarArticulo)

    def retranslateUi(self, DlgRegistrarArticulo):
        _translate = QtCore.QCoreApplication.translate
        DlgRegistrarArticulo.setWindowTitle(_translate("DlgRegistrarArticulo", "Registrar Articulo"))
        self.LblDatos.setText(_translate("DlgRegistrarArticulo", "Datos del Articulo"))
        self.LblCodigo.setText(_translate("DlgRegistrarArticulo", "Codigo:"))
        self.LblNombre.setText(_translate("DlgRegistrarArticulo", "Nombre:"))
        self.LblPrecio.setText(_translate("DlgRegistrarArticulo", "Precio: "))
        self.LblCantidad.setText(_translate("DlgRegistrarArticulo", "Cantidad: "))
        self.BtnResgistrar.setText(_translate("DlgRegistrarArticulo", "Registrar"))
