# Form implementation generated from reading ui file 'IngresoArticulosBodega.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_IngresoaBodega(object):
    def setupUi(self, IngresoaBodega):
        IngresoaBodega.setObjectName("IngresoaBodega")
        IngresoaBodega.resize(448, 366)
        self.CmbBodegas = QtWidgets.QComboBox(parent=IngresoaBodega)
        self.CmbBodegas.setGeometry(QtCore.QRect(20, 300, 111, 22))
        self.CmbBodegas.setObjectName("CmbBodegas")
        self.LblBodegas = QtWidgets.QLabel(parent=IngresoaBodega)
        self.LblBodegas.setGeometry(QtCore.QRect(20, 280, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblBodegas.setFont(font)
        self.LblBodegas.setObjectName("LblBodegas")
        self.LblIngreso = QtWidgets.QLabel(parent=IngresoaBodega)
        self.LblIngreso.setGeometry(QtCore.QRect(20, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LblIngreso.setFont(font)
        self.LblIngreso.setObjectName("LblIngreso")
        self.TblArticulosNoRegistrados = QtWidgets.QTableWidget(parent=IngresoaBodega)
        self.TblArticulosNoRegistrados.setEnabled(True)
        self.TblArticulosNoRegistrados.setGeometry(QtCore.QRect(10, 50, 421, 221))
        self.TblArticulosNoRegistrados.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.TblArticulosNoRegistrados.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.TblArticulosNoRegistrados.setObjectName("TblArticulosNoRegistrados")
        self.TblArticulosNoRegistrados.setColumnCount(4)
        self.TblArticulosNoRegistrados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TblArticulosNoRegistrados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TblArticulosNoRegistrados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TblArticulosNoRegistrados.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TblArticulosNoRegistrados.setHorizontalHeaderItem(3, item)
        self.BtnIngresarArticulos = QtWidgets.QPushButton(parent=IngresoaBodega)
        self.BtnIngresarArticulos.setGeometry(QtCore.QRect(330, 290, 111, 61))
        self.BtnIngresarArticulos.setObjectName("BtnIngresarArticulos")

        self.retranslateUi(IngresoaBodega)
        QtCore.QMetaObject.connectSlotsByName(IngresoaBodega)

    def retranslateUi(self, IngresoaBodega):
        _translate = QtCore.QCoreApplication.translate
        IngresoaBodega.setWindowTitle(_translate("IngresoaBodega", "Dialog"))
        self.LblBodegas.setText(_translate("IngresoaBodega", "Bodega"))
        self.LblIngreso.setText(_translate("IngresoaBodega", "Ingresar articulos a bodegas"))
        item = self.TblArticulosNoRegistrados.horizontalHeaderItem(0)
        item.setText(_translate("IngresoaBodega", "Codigo"))
        item = self.TblArticulosNoRegistrados.horizontalHeaderItem(1)
        item.setText(_translate("IngresoaBodega", "Nombre"))
        item = self.TblArticulosNoRegistrados.horizontalHeaderItem(2)
        item.setText(_translate("IngresoaBodega", "Precio"))
        item = self.TblArticulosNoRegistrados.horizontalHeaderItem(3)
        item.setText(_translate("IngresoaBodega", "Cantidad"))
        self.BtnIngresarArticulos.setText(_translate("IngresoaBodega", "Guardar en Bodega"))
